from django.conf.urls import patterns, url,include
from radar import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^add_offer/$', views.add_offer, name='add_offer'),
                       url(r'^add_basket/(?P<offer_id>[\w\-]+)/$', views.add_basket, name='add_basket'),
                       url(r'^basket/$', views.basket, name='basket'),
                       # url(r'^blog/$', views.blog, name='blog'),
                       url(r'^checkout/$', views.checkout, name='checkout'),
                       url(r'^client_offers/$', views.client_offers, name='client_offers'),
                       url(r'^contact/$', views.contact, name='contact'),
                       url(r'^details/$', views.details, name='details'),
                       url(r'^error/$', views.error, name='error'),
                       url(r'^login/$', views.showLogin, name='login'),
                       url(r'^offer/(?P<offer_id>[\w\-]+)/$', views.offer, name='offer'),
                       url(r'^register/$', views.register, name='register'),
                       url(r'^remove_basket/(?P<offer_id>[\w\-]+)/$', views.remove_basket, name='remove_basket'),
                       url(r'^remove_offer/(?P<offer_id>[\w\-]+)/$', views.remove_offer, name='remove_offer'),
                       url(r'^shop/$', views.shop, name='shop'),
                       # url(r'^single_blog/$', views.single_blog, name='single_blog'),
                       url(r'^user_login/$', views.user_login, name='user_login'),
                       url(r'^user_logout/$', views.user_logout, name='user_logout'),
                       url(r'^[a-zA-Z0-9/]+$', views.error, name='error'),
                       )
